micronaut:
  application:
    name: teste_swagger
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc-ui
        mapping: /redoc/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    schema-generate: CREATE_DROP
    db-type: postgres
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
